[package]
name = "gen-color-spring-night"
version = "0.0.0"
authors = ["rhysd <lin90162@yahoo.co.jp>"]
publish = false
edition = "2018"

[dependencies]
getopts = "0.2"
anyhow = "1"

[dev-dependencies]
regex = "1"
